version: 2
jobs:
  build:
    working_directory: ~/dobtco/formrenderer-base
    parallelism: 1
    docker:
      - image: circleci/node:6.14.3
    steps:
      - checkout

      - restore_cache:
          key: formrenderer-dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install grunt-cli
          command: npm install grunt-cli

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: formrenderer-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: test
          command: npm test
          
      - store_artifacts:
          path: test-results.xml
          prefix: tests

      - store_test_results:
          path: test-results.xml
