#!/bin/sh

version=$1

if [ -n "$version" ]; then
  echo "FormRenderer.VERSION = '$version'" > src/version.coffee
  git add src/version.coffee
  git commit -am "Bumped version to $version"
else
  echo "Please provide version number as the first argument."
  exit 22
fi
