#!/bin/sh

version=$1

if [ -z "$version" ]; then
  echo 'You must pass a semantic version number as the first (and only) argument.'
  exit 1
fi

set -e

echo "FormRenderer.VERSION = '$version'" > src/version.coffee
grunt all
grunt test
git commit -am "release $version"
git push origin master --tags
grunt s3:version
grunt s3:autoupdate

# Create a new gem on rails-assets
curl -H "Content-Type: application/json" \
     -X POST \
     -d "{ \"component\": { \"name\": \"formrenderer-base\", \"version\": \"$version\" } }" \
     "https://rails-assets.org/components"

echo "All done! Consider drafting a new release on GitHub: \n\n" \
     "https://github.com/dobtco/formrenderer-base/releases/new"
