name: Bump Package Version and Deploy to S3
on: [push]
jobs:
  bump-version:
    name: Bump version on master
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Automated version bump
        uses: phips28/gh-action-bump-version@v8.0.12
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: "cat package.json"
        run: cat ./package.json
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.3.1
    - name: Install sass
      run: gem install sass
    - uses: actions/setup-node@v1
      with:
        node-version: 6.11.4
    - name: script/bootstrap
      run: script/bootstrap
    - name: Get version
      run: |
            curl -H "Content-Type: application/json" \
            -X POST \
            -d "{ \"component\": { \"name\": \"formrenderer-base\", \"version\": \"$version\" } }" \
            "https://rails-assets.org/components"
    - name: Pull latest vesion
      run: git pull
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: test version
      run: echo "version is ${{ steps.package-version.outputs.current-version}}"
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: staging-formrenderer-base
        AWS_ACCESS_KEY_ID: ${{ secrets.DOBT_FORM_RENDERER_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DOBT_FORM_RENDERER_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: './dist'
        DEST_DIR: ${{ steps.package-version.outputs.current-version}}
